name: CI

on:
  pull_request:

jobs:
  build:
    name: Develop Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --verbose

      - name: Run linting
        run: npm run lint

      - name: Format code
        run: npx prettier --check .

      - name: Complete PR check
        if: success()
        run: echo "Pipeline completed successfully!"
