name: CI

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
            npm install --save-dev prettier

      - name: Run tests
        run: npm test -- --verbose
      
      - name: Run linting
        run: npm init @eslint/config
             npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Format code
        run: npx prettier --write '**/*.{js,json,yml}' 

      - name: Complete PR check
        if: success()
        run: echo "Pipeline completed successfully!"
