name: CI

on:
  pull_request:
jobs:
  build:
    name: Status Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
            npm install --save-dev prettier

      - name: Run tests
        run: npm test -- --verbose
      
      - name: Run linting
        run: npm init @eslint/config
             npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write *.js

      - name: Complete PR check
        if: success()
        run: echo "Pipeline completed successfully!"
