name: CI

on:
  pull_request:
jobs:
  build:
    name: Status Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --verbose
      
      - name: Run linting
        run: npm init @eslint/config
             npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Prettify code
        run: npx prettier --write '*.js'
      - name: Commit formatted files
        run: git add . && git diff-index --quiet HEAD || git commit -m "Prettier formatting"

      - name: Push changes
        run: git push
